#!/system/bin/sh
ui_print "      ______________________________________"
ui_print "     /                                      \\"
ui_print "    |   _   _  ____  __  __  ___            |"
ui_print "    |  | | | ||  _ \\|  \\/  ||_ _|           |"
ui_print "    |  | |_| || | | | |\\/| | | |            |"
ui_print "    |  |  _  || |_| | |  | | | |            |"
ui_print "    |  |_| |_||____/|_|  |_| |___|          |"
ui_print "    |                                      |"
ui_print "    |  || || || || || || || || || || ||    |"
ui_print "     \\____________________________________/"
ui_print ""
ui_print "- LineageOS TV / BlissOS 17 HDMI Sound Fixer v1.1 by BugDroid"
ui_print ""
ui_print "- Stage : late_start service (non blocking)"
ui_print "- set androidboot.hdmi_audio=1 and syscall_hardening=off in grub cmdline to make it work"
ui_print "- logs: /data/local/tmp/ksu_boot_cmd.log"
